version: "3.7"

services:
  sockshop-db:
    image: mysql:5.7.34
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: socksdb
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: sockshop
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - sockshop-db-vol:/var/lib/mysql
      - ${PWD}/deploy/docker/sockshop-db:/docker-entrypoint-initdb.d

  sockshop:
    image: golang:1.22.0
    command: >
      bash -c "make build-linux 
      && ./bin/linux-amd64/sockshop --mysql-conn-str 'sockshop:password@tcp(sockshop-db:3306)/socksdb'"
    working_dir: /sockshop
    init: true
    ports:
      - 9090:9090
    environment:
      KEY: value
    volumes:
      - ${PWD}:/sockshop
      - go-mod-cache:/go/pkg/mod
    depends_on:
      - sockshop-db
    healthcheck:
      test: curl --fail http://localhost:9090/health || exit 1
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 60s

# Names our volume
volumes:
  sockshop-db-vol:
  go-mod-cache:
